baseURL = "https://dalebeast.com/"
languageCode = "en-us"
title = "My Author Site"
author = "Dale Beast"
copyright = "© 2025 Dale Beast. All rights reserved."
theme = "PaperMod"
enableRobotsTXT = true
